### ISSUE TITLE
C++ XML feeds are broken.

### ISSUE THREAD

**Issue by natebenes** [oscardelben/github-trends#1]
When trying to get the XML feeds for C++, the app returns a 404.  Does this have something to do with the '+'s getting encoded?

**Comment by spaetzel** [comment]
The C# feeds are also broken. Replacing the # with %23 results in the same problem

**Comment by oscardelben** [comment]
Yes this is an encoding error which I'm trying to solve. Thanks for the heads up

**Comment by oscardelben** [comment]
This should be solved, thanks again.
