### ISSUE TITLE
Broken links on github-trends again

### ISSUE THREAD

**Issue by wyngit** [oscardelben/github-trends#10]
Hello! Just to let you know that the links are broken as of August 20th. 

Trying to wget the RSS feed gives this message:

Resolving github-trends.oscardelben.com (github-trends.oscardelben.com)... 107.22.233.248, 50.16.215.41, 107.21.105.64, ...
Connecting to github-trends.oscardelben.com (github-trends.oscardelben.com)|107.22.233.248|:80... connected.
HTTP request sent, awaiting response... 500 Internal Server Error
2013-08-22 15:41:01 ERROR 500: Internal Server Error.

**Comment by oscardelben** [comment]
Hi,

I think they've been broken for some time, haven't had the chance to fix them as I'm not using it anymore. I'll take a look if I have time but from what I remember github changed their dom and the whole things has to be modified.

**Comment by oscardelben** [comment]
Hi, this likely wont get fixed, at least by me. Best bet is see if they added some kind of rss feed.

**Comment by wyngit** [comment]
Alrighty thank you. This is a pity though...
